/**
 * Marketplace Content Moderation – Keyword Blocklist
 * Covers English and Filipino (Tagalog) profanity, adult content,
 * scam phrases, spam phrases, and prohibited item keywords.
 *
 * All entries are lowercase. Matching is done case-insensitively with
 * whole-word or substring matching depending on the entry.
 */

// ---------------------------------------------------------------------------
// ENGLISH
// ---------------------------------------------------------------------------
export const ENGLISH_BLOCKLIST: string[] = [
    // --- Profanity ---
    'fuck',
    'fucker',
    'fucking',
    'fucked',
    'fuk',
    'fuking',
    'fck',
    'shit',
    'shitty',
    'bullshit',
    'asshole',
    'ass hole',
    'bitch',
    'bastard',
    'cunt',
    'dick',
    'cock',
    'pussy',
    'whore',
    'slut',
    'nigger',
    'nigga',
    'faggot',
    'retard',
    'motherfucker',
    'motherfucking',
    'son of a bitch',

    // --- Adult / Sexual Content ---
    'porn',
    'pornography',
    'xxx',
    'sex video',
    'nude',
    'nudes',
    'naked',
    'onlyfans',
    'escort',
    'prostitute',
    'prostitution',
    'call girl',
    'erotic',
    'orgasm',
    'cum',

    // --- Scam / Fraud Phrases ---
    'send money first',
    'gcash first',
    'transfer first',
    'pay first',
    'western union',
    'money gram',
    'bitcoin payment',
    'crypto payment',
    'advance payment required',
    'downpayment first',
    'too good to be true',
    'guaranteed profit',
    'double your money',
    'earn from home no experience',
    'no experience needed earn',
    'work from home earn',
    'unlimited income',
    'easy money',
    'fast cash',
    'financial freedom guaranteed',
    'make money fast',
    'wire transfer',

    // --- Spam / MLM Phrases ---
    'buy followers',
    'increase followers',
    'social media boost',
    'fake reviews',
    'mlm',
    'multilevel marketing',
    'pyramid scheme',
    'join my team earn',
    'passive income guaranteed',

    // --- Prohibited Items ---
    'gun for sale',
    'pistol for sale',
    'rifle for sale',
    'grenade',
    'ammunition',
    'live ammo',
    'explosives',
    'cocaine',
    'heroin',
    'methamphetamine',
    'meth for sale',
    'shabu',
    'illegal drugs',
    'marijuana for sale',
    'weed for sale',
    'cannabis for sale',
    'counterfeit',
    'fake money',
    'fake bill',
    'stolen goods',
    'carnapped',
    'hijacked vehicle',
];

// ---------------------------------------------------------------------------
// FILIPINO / TAGALOG
// ---------------------------------------------------------------------------
export const TAGALOG_BLOCKLIST: string[] = [
    // --- Profanity ---
    'putangina',
    'putang ina',
    'putang ina mo',
    'puta',
    'puta ka',
    'gago',
    'gaga',
    'tanga',
    'bobo',
    'boba',
    'tarantado',
    'punyeta',
    'ulol',
    'leche',
    'pakyu',
    'pak yu',
    'bwisit',
    'hayop ka',
    'animal ka',
    'inutil',
    'imbecil',
    'engot',
    'lintik',
    'lintik ka',
    'siraulo',
    'buang',
    'ampota',
    'ampotah',
    'tangina',
    'tang ina',
    'kupal',
    'hunghang',
    'estupido',
    'tae',
    'pekpek',
    'burat',
    'titi',
    'kantot',
    'jakol',
    'kantutan',
    'masturbasyon',
    'libog',

    // --- Adult / Sexual Content ---
    'bold na pelikula',
    'hubad',
    'hubad na larawan',
    'sex video tagalog',
    'kabit',
    'kirhing',

    // --- Scam / Fraud Phrases ---
    'paunang bayad',
    'ipadala mo muna ang pera',
    'magpadala muna ng bayad',
    'bago maipadala',
    'libre na libreng pera',
    'doblehin ang pera',
    'sure na kikita',
    'walang puhunan kikita ka',
    'kikita ka agad',
    'pautang online',
    'legit na negosyo walang puhunan',
    'walang puhunan malaking kita',

    // --- Spam / MLM ---
    'sumali sa aming network',
    'maging miyembro at kumita',
    'mamuhunan at kumita',
    'rekruto at kikita',
    'downline',

    // --- Prohibited Items ---
    'droga',
    'shabu',
    'mapagtanggap ng shabu',
    'baril',
    'tangki',
    'patalim na ipinagbabawal',
    'granada',
    'bomba',
    'pekeng pera',
    'pekeng barya',
    'nakawin',
    'ninakaw',
    'produktong ninakaw',
];
